Accounts/urls.py
from django.urls import path 

from. import views

# app_name = "accounts"

urlpatterns = [
    path("register/", views.register_request, name="register"),
    path("login/", views.login_request, name="login"),
    path('logout/', views.logout_request, name='logout'),
    path("profile/", views.edit_user, name="profile"),
    path("password_reset/", views.password_reset_request, name="password_reset"),
    path('password_reset/done/', views.password_reset_done_request, name='password_reset_done'),
    path('reset/<uidb64>/<token>/', views.password_reset_confirm_request, name='password_reset_confirm'),
    path('reset/done/', views.password_reset_complete_request, name='password_reset_complete'),
    path('post/<int:pk>/comment', views.post_comment_request, name='comment'),
    path('delete/<int:pk>/comment/', views.delete_comment, name='delete_comment'),
    path("search_user/", views.search_user, name="search_user"),
    path("user_home/", views.user_home, name="user_home"),
    ]

Details/urls.py
from django.urls import path
from. import views


app_name = "Details"

urlpatterns = [
    path("create_post/", views.create_post, name="create_post"),
    path("update_post/<int:id>/", views.update_post, name="update_post"),
    path("delete_post/<int:id>/", views.delete_post, name="delete_post"),
    path('like_post/<post_id>/', views.like_post, name='like_post'),
    path('unlike_post/<post_id>/', views.unlike_post, name='unlike_post'),
    path('send_message/', views.send_message, name='send_message'),
    path('send_user_message/<int:id>', views.send_user_message, name='send_user_message'),
    path('search_post/', views.search_post, name='search_post'),

    # Mock URLs.
    path('view_posts_mock/', views.view_posts_mock, name='view_posts_mock'),
    path('view_posts_mock/<post_id>/', views.view_post_mock, name='view_post_mock'),
]

mysite/mysite/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('SMA.urls'))
]

sma_project/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static
from django.conf import settings
from Accounts import views


urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('accounts/', include('Accounts.urls')),
    path('details/', include('Details.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Accounts/models.py
from django.db import models
from datetime import datetime
from django.contrib.auth.models import AbstractUser
from django.conf import settings


# Create your models here.


class User(AbstractUser):
    class AccountStatus(models.TextChoices):
        LOCKED = 'Locked', 'Locked'
        UNLOCKED = 'Unlocked', 'Unlocked'

    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=255, unique=True, null=True, blank=True, default=None)
    email = models.EmailField(max_length=255, unique=True, null=True, blank=True, default=None)
    first_name = models.CharField(max_length=255, null=True, blank=True, default=None)
    last_name = models.CharField(max_length=255, null=True, blank=True, default=None)
    occupation = models.CharField(max_length=255, null=True, blank=True, default=None)
    bio = models.TextField(null=True, blank=True, default=None)
    verified = models.BooleanField(default=False, null=True, blank=True)
    account_status = models.CharField(max_length=10, choices=AccountStatus.choices, default=AccountStatus.UNLOCKED, null=True, blank=True)
    followers_count = models.IntegerField(default=0, null=True, blank=True)
    follows_count = models.IntegerField(default=0, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.email


class UserSocial(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True, default=None)
    facebook_link = models.CharField(max_length=255, null=True, blank=True, default=None)
    instagram_link = models.CharField(max_length=255, null=True, blank=True, default=None)
    twitter_link = models.CharField(max_length=255, null=True, blank=True, default=None)
    linkedin_link = models.CharField(max_length=255, null=True, blank=True, default=None)
    github_link = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self) -> str:
        return self.user_id.username


class PasswordReset(models.Model):
    id = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True, default=None)
    token = models.CharField(max_length=50, unique=True, null=True, blank=True, default=None)
    token_used = models.BooleanField(default=False, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField(null=True, blank=True, default=None)

    class Meta:
        verbose_name_plural = "Password Resets"
        ordering = ['user_id']

Accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import fields_for_model
from .models import UserSocial

class UserProfileForm(ModelForm):
    class Meta:
        model = UserSocial
        fields=['facebook_link','instagram_link','twitter_link','linkedin_link','github_link']
        

Accounts/views.py
from django.db.models.query_utils import Q
from django.http import HttpResponse
from django.shortcuts import  render, redirect
from django.contrib.auth import login, authenticate,logout
from django.contrib import messages #import messages
from .models import User, PasswordReset
from Details.models import Follower
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.auth.decorators import login_required

from .models import UserSocial
from .forms import UserProfileForm

from django.core.mail import send_mail, BadHeaderError
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes, force_text
from Details.models import Post, PostComment

from django.shortcuts import get_object_or_404


# Create your views here.

def index(request):
    #return HttpResponse("Welcome, this is the SMA app")
    if request.user.is_authenticated:
        return redirect("user_home")
    return render (request=request, template_name="landing.html")

@login_required()
def user_home(request):
    #return HttpResponse("Welcome, this is the SMA app")
	return render (request=request, template_name="user_home.html")

def register_request(request):
    if request.user.is_authenticated:
        return redirect("user_home")
        
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        confirmpwd = request.POST.get('conf_password')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        email = request.POST.get('email')

        if password == confirmpwd:
            try:
                user = User.objects.get(email=email)
                messages.error(request, "Email already exists")
                return redirect("register")
            except User.DoesNotExist:
                user = User.objects.create_user(email=email, username=username, password=password, first_name=first_name, last_name=last_name)
                user.save()
                messages.success(request, "Registration successful")
                return redirect("index")
        messages.error(request, "Unsuccessful registration. Invalid information.")
    return render(request=request, template_name="register.html")




def login_request(request):

    if request.user.is_authenticated:
        return redirect("user_home")

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            messages.info(request, f"You are now logged in as {username}.")
            return redirect("user_home")
        else:
            messages.error(request,"Invalid username or password.")
            return redirect("login")

    return render(request, "landing.html")





def logout_request(request):
    if request.user.is_authenticated:
        logout(request)
        messages.info(request, f"You are now logged out.")
        return redirect("login")

    return render(request, "landing.html")


@login_required()
def edit_user(request):
    if request.method == 'POST':
        form = UserProfileForm(request.POST,instance=UserSocial)
        if form.is_valid():
            form.save()
            messages.success(request,'Your Profile has been updated!')
            return redirect('profile')
    else:
        form = UserProfileForm(instance=UserSocial)
        context = {'form': form}
        return render(request=request, template_name="profile.html", context=context)

    messages.error(request,"Invalid username or password.")
    return render(request=request, template_name="login.html")




def password_reset_request(request):

    if request.method == "POST":
        email = request.POST['email']
        user = User.objects.filter(email=email).first()

        # Record token in PasswordReset model
        token = default_token_generator.make_token(user)
        passwordResetModel = PasswordReset.objects.create(user_id=user, token=token)
        passwordResetModel.save()

        # Create and send e-mail
        subject = "Password Reset Requested"
        email_template_name = "password_reset_email.txt"
        c = {
            "email": user.email,
            "domain": "127.0.0.1:8000",
            "site_name": "SMA Team 2",
            "uid": urlsafe_base64_encode(force_bytes(user.pk)),
            "user": user,
            "token": token,
            "protocol": "http",
        }

        email = render_to_string(email_template_name, c)
        try:
            send_mail(subject, email, "team2@sma.com", [user.email], fail_silently=False)
        except BadHeaderError:
            return HttpResponse("Invalid header found.")
        return redirect("password_reset_done")

    return render(request=request, template_name="password_reset.html")


def password_reset_done_request(request):
    return render(request=request, template_name="password_reset_done.html")


def password_reset_confirm_request(request, uidb64, token):
    user_id = force_text(urlsafe_base64_decode(uidb64))
    user = User.objects.filter(id=user_id).first()

    if request.method == "POST":
        password = request.POST['password']
        confirmpwd = request.POST['conf_password']

        if password == confirmpwd:
            user.set_password(password)
            user.save()

            passwordResetModel = PasswordReset.objects.filter(user_id=user, token=token).first()
            passwordResetModel.token_used = True
            passwordResetModel.save()

            return render(request=request, template_name="password_reset_complete.html")
        else:
            messages.error(request, "Passwords do not match.")

    else:
        passwordResetModel = PasswordReset.objects.filter(user_id=user, token=token).first()

        if passwordResetModel.token_used == True:
            return HttpResponse("Token has already been used.")

    return render(request=request, template_name="password_reset_confirm.html")


def password_reset_complete_request(request):
    return render(request=request, template_name="password_reset_complete.html")


@login_required()
def post_comment_request(request, pk):

    try:
        post = Post.objects.get(id=pk)
    except Post.DoesNotExist:
        messages.error("Post does not exist")
        return redirect("index")

    if request.method == "POST":
        comment = request.POST['comment']
        session_user = request.user
        user = User.objects.get(email=session_user)
        post_comment = PostComment(commenter_id=user, post_id=post, content=comment)
        post_comment.save()
        messages.success(request, "Comment successfully posted")
        return redirect("index")

    return render(request, "comment.html", {'post':post})


@login_required()
def delete_comment(request, id):
    comment = get_object_or_404('Comment', id=id)
    try:
        comment.delete()
        messages.success(request, 'You have successfully deleted the comment')
    except:
        messages.warning(request, 'The comment could not be deleted.')
    return redirect("index")


@login_required()
def follow_user(request, user_name):
    other_user = User.objects.get(username=user_name)
    session_user = request.session['user']
    get_user = User.objects.get(username=session_user)
    check_follower = Follower.objects.get(username=get_user.id)
    is_followed = False
    if other_user.username != session_user:
        if check_follower.follower_id.filter(username=other_user).exists():
            add_usr = Follower.objects.get(username=get_user)
            add_usr.follower_id.remove(other_user)
            is_followed = False
            return redirect(f'/profile/{session_user}')
        else:
            add_usr = Follower.objects.get(username=get_user)
            add_usr.follower_id.add(other_user)
            is_followed = True
            return redirect(f'/profile/{session_user}')
 
    else:
        return redirect(f'/profile/{session_user}')


@login_required()
def search_user(request):

    if request.method == "POST":
        query = request.POST['query']

        if query:
            users = User.objects.filter(username__contains=query)

            if users:
                for user in users:
                    messages.info(request, user.username)

            else:
                messages.error(request, "Username not found")

            return render(request=request, template_name="search_user.html")

        else:
            print("Please type username")
            return render(request=request, template_name="search_user.html")

    return render(request=request, template_name="search_user.html")

Accounts/templates/comment.html
{% extends "header.html" %}

{% block content %} 
  

<!--Comment--> 
<div class="container py-5">
	<h1>Comments</h1>
	<!-- pass the post.id to the view-->
	<form action="{% url 'comment' post.id %}" method="POST">
		{% csrf_token %}
		<h3>Post</h3>
        <textarea>{{ post.content }}</textarea>
        <br>
        <br>
        <textarea name="comment"></textarea>
		<input type="submit" value="Comment"/>
	</form>
</div>

{% endblock %}

Accounts/templates/dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Twitter Clone - Final</title>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
      integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'dashboard/styles.css' %}" />
  </head>
  <body>
    <!-- sidebar starts -->
    <div class="sidebar">
      <i class="fab fa-twitter"></i>
      <div class="sidebarOption active">
        <span class="material-icons"> home </span>
        <h2>Home</h2>
      </div>

      <div class="sidebarOption">
        <span class="material-icons"> search </span>
        <h2>Explore</h2>
      </div>

      <div class="sidebarOption">
        <span class="material-icons"> notifications_none </span>
        <h2>Notifications</h2>
      </div>

      <div class="sidebarOption">
        <span class="material-icons"> mail_outline </span>
        <h2>Messages</h2>
      </div>

      <div class="sidebarOption">
        <span class="material-icons"> bookmark_border </span>
        <h2>Bookmarks</h2>
      </div>

      <div class="sidebarOption">
        <span class="material-icons"> list_alt </span>
        <h2>Lists</h2>
      </div>

      <div class="sidebarOption">
        <span class="material-icons"> perm_identity </span>
        <h2>Profile</h2>
      </div>

      <div class="sidebarOption">
        <span class="material-icons"> more_horiz </span>
        <h2>More</h2>
      </div>
      <button class="sidebar__tweet">Tweet</button>
    </div>
    <!-- sidebar ends -->

    <!-- feed starts -->
    <div class="feed">
      <div class="feed__header">
        <h2>Home</h2>
      </div>

      <!-- tweetbox starts -->
      <div class="tweetBox">
        <form>
          <div class="tweetbox__input">
            <img
              src="https://i.pinimg.com/originals/a6/58/32/a65832155622ac173337874f02b218fb.png"
              alt=""
            />
            <input type="text" placeholder="What's happening?" />
          </div>
          <button class="tweetBox__tweetButton">Tweet</button>
        </form>
      </div>
      <!-- tweetbox ends -->

      <!-- post starts -->
      <div class="post">
        <div class="post__avatar">
          <img
            src="https://i.pinimg.com/originals/a6/58/32/a65832155622ac173337874f02b218fb.png"
            alt=""
          />
        </div>

        <div class="post__body">
          <div class="post__header">
            <div class="post__headerText">
              <h3>
                Somanath Goudar
                <span class="post__headerSpecial"
                  ><span class="material-icons post__badge"> verified </span>@somanathg</span
                >
              </h3>
            </div>
            <div class="post__headerDescription">
              <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit.</p>
            </div>
          </div>
          <img
            src="https://www.focus2move.com/wp-content/uploads/2020/01/Tesla-Roadster-2020-1024-03.jpg"
            alt=""
          />
          <div class="post__footer">
            <span class="material-icons"> repeat </span>
            <span class="material-icons"> favorite_border </span>
            <span class="material-icons"> publish </span>
          </div>
        </div>
      </div>
      <!-- post ends -->

      <!-- post starts -->
      <div class="post">
        <div class="post__avatar">
          <img
            src="https://i.pinimg.com/originals/a6/58/32/a65832155622ac173337874f02b218fb.png"
            alt=""
          />
        </div>

        <div class="post__body">
          <div class="post__header">
            <div class="post__headerText">
              <h3>
                Somanath Goudar
                <span class="post__headerSpecial"
                  ><span class="material-icons post__badge"> verified </span>@somanathg</span
                >
              </h3>
            </div>
            <div class="post__headerDescription">
              <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit.</p>
            </div>
          </div>
          <img
            src="https://www.focus2move.com/wp-content/uploads/2020/01/Tesla-Roadster-2020-1024-03.jpg"
            alt=""
          />
          <div class="post__footer">
            <span class="material-icons"> repeat </span>
            <span class="material-icons"> favorite_border </span>
            <span class="material-icons"> publish </span>
          </div>
        </div>
      </div>
      <!-- post ends -->
    </div>
    <!-- feed ends -->

    <!-- widgets starts -->
    <div class="widgets">
      <div class="widgets__input">
        <span class="material-icons widgets__searchIcon"> search </span>
        <input type="text" placeholder="Search Twitter" />
      </div>

      <div class="widgets__widgetContainer">
        <h2>What's happening?</h2>
        <blockquote class="twitter-tweet">
          <p lang="en" dir="ltr">
            Sunsets don&#39;t get much better than this one over
            <a href="https://twitter.com/GrandTetonNPS?ref_src=twsrc%5Etfw">@GrandTetonNPS</a>.
            <a href="https://twitter.com/hashtag/nature?src=hash&amp;ref_src=twsrc%5Etfw"
              >#nature</a
            >
            <a href="https://twitter.com/hashtag/sunset?src=hash&amp;ref_src=twsrc%5Etfw"
              >#sunset</a
            >
            <a href="http://t.co/YuKy2rcjyU">pic.twitter.com/YuKy2rcjyU</a>
          </p>
          &mdash; US Department of the Interior (@Interior)
          <a href="https://twitter.com/Interior/status/463440424141459456?ref_src=twsrc%5Etfw"
            >May 5, 2014</a
          >
        </blockquote>
        <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      </div>
    </div>
    <!-- widgets ends -->
  </body>
</html>

Accounts/templates/header.html
<!DOCTYPE html>
<html>
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>SMA App</title>
  </head>
 <body>

    {% include 'includes/messages.html' %}

    {% block content %}

    {% endblock %} 
      
  </body>
</html>

Accounts/templates/home.html
{% extends "header.html" %}

{% block content %} 

<h1>Welcome, this is the SMA APP</h1>

[ <a href="{% url 'login' %}">login</a> | <a href="{% url 'register' %}">register</a> ]

{% endblock %}

Accounts/templates/login.html
{% extends "header.html" %}

{% block content %} 
  

<!--Login--> 
<div class="container py-5">
	<h1>Login</h1>
	<form action="{% url 'login' %}" method="POST">
		{% csrf_token %}
		Username: <input type="text" name="username" required/><br/>
		Password: <input type="password" name="password" required/><br/> 
		<input type="submit" value="Login"/>
	</form>
	<p class="text-center">Don't have an account? <a href="/accounts/register">Register</a> instead.</p>
	<br>
	<p class="text-center">Forgot your password? <a href="/accounts/password_reset">Reset your password</a>.</p>
</div>

{% endblock %}

Accounts/templates/password_reset.html
{% extends "header.html" %}

{% block content %} 
  

<!--Password Reset--> 
<div class="container py-5">
	<h1>Reset Password</h1>
	<p>Forgot your password? Enter your e-mail address below and we'll e-mail you instructions for resetting it.</p>
	<form method="POST">
		{% csrf_token %}
		E-mail: <input type="text" name="email" required/>
		<input type="submit" value="Submit"/>
	</form>
</div>

{% endblock %}

Accounts/templates/password_reset_complete.html
{% extends "header.html" %}

{% block content %} 
  

<!--Password Reset Complete--> 
<div class="container py-5">
	<h1>Reset Password</h1>
	<p>Your password has been set. Go ahead and <a href="/accounts/login">log in</a> using the new password.</p>
</div>

{% endblock %}

Accounts/templates/password_reset_confirm.html
{% extends "header.html" %}

{% block content %} 
  

<!--Password Reset Confirm--> 
<div class="container py-5">
	<h1>Reset Password</h1>
	<p>Please enter your new password.</p>
	<form method="POST">
		{% csrf_token %}
		Enter New Password: <input type="password" name="password" required/><br/>
		Confirm New Password: <input type="password" name="conf_password" required/><br/>
		<input type="submit" value="Reset"/>
	</form>
</div>

{% endblock %}

Accounts/templates/post_search.html
{% extends "header.html" %}

{% block content %} 
  

<!--Password Reset--> 
<div class="container py-5">
	<h1>Post Search</h1>
	<p>Looking for a particular post? Enter keywords in the search bar below.</p>
	<form method="POST">
		{% csrf_token %}
		keywords: <input type="text" name="keywords" required/>
		<input type="submit" value="Submit"/>
	</form>
</div>

{% endblock %}

Accounts/templates/post_search_result.html
{% extends "header.html" %}

{% block content %} 
  

<!--Password Reset--> 
<div class="container py-5">
	<h1>Post Search</h1>
	<p>Looking for a particular post? Enter keywords in the search bar below.</p>
	<form method="POST">
		{% csrf_token %}
		keywords: <input type="text" name="keywords" required/>
		<input type="submit" value="Submit"/>
	</form>
</div>

{% endblock %}

Accounts/templates/profile.html
{% extends "header.html" %}

{% block content %} 
  

<!--Login--> 
<div class="container py-5">
	<h1>Profile</h1>
	<form action="{% url 'profile' %}" method="POST">
		{% csrf_token %}
		Facebook: <input type="text" name="Facebook link" ><br/>
		Instagram: <input type="text" name="Instagram link" ><br/> 
        Twitter: <input type="text" name="Twitter link" ><br/> 
        Linkedin: <input type="text" name="Linkedin link" ><br/> 
        Github: <input type="text" name="Github link" ><br/> 
		<input type="submit" value="Update"/>
	</form>
	<br>
	<br>
	<br>
	<p>Return to <a href="/accounts/user_home">user home</a></p>
</div>

{% endblock %}

Accounts/templates/register.html
{% extends "header.html" %}

{% block content %} 
  

<!--Register--> 
<div class="container py-5">
	<h1>Register</h1>
	<form action="{% url 'register' %}" method="POST">
		{% csrf_token %}
		Username: <input type="text" name="username" required/><br/>
		First Name: <input type="text" name="first_name" required/><br/>
		Last Name: <input type="text" name="last_name" required/><br/>
		Email: <input type="email" name="email" required/><br/>
		Password: <input type="password" name="password" required/><br/>
		Confirm Password: <input type="password" name="conf_password" required/><br/>
		<input type="submit" value="Register"/>
	</form>
	<p class="text-center">If you already have an account, <a href="/accounts/login">login</a> instead.</p>
</div>

{% endblock %}

Accounts/templates/search_user.html
{% extends "header.html" %}

{% block content %} 
  


<div class="container py-5">
	<h1>User Search</h1>
	<p>Looking for a user? Enter the username in the search bar below.</p>
	<form action="{% url 'search_user' %}" method="POST">
		{% csrf_token %}
		username: <input type="text" name="query" required/>
		<input type="submit" value="Search"/>
	</form>
	<br>
	<br>
	<br>
	<p>Return to <a href="/accounts/user_home">user home</a></p>
</div>

{% endblock %}

Accounts/templates/user_home.html
{% extends "header.html" %}

{% block content %} 

<h1>Welcome, this is the SMA APP</h1>

[ <a href="{% url 'profile' %}">profile</a> | <a href="{% url 'search_user' %}">search user</a> | <a href="{% url 'Details:view_posts_mock' %}">view posts (mock)</a> | <a href="{% url 'Details:create_post' %}">create post</a> | <a href="{% url 'Details:search_post' %}">search post</a> | <a href="{% url 'logout' %}">logout</a> ]

{% endblock %}